# Generated by Django 5.1.3 on 2024-12-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('gps', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('hourly', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('ppe', models.CharField(blank=True, max_length=255, null=True)),
                ('tools', models.CharField(blank=True, max_length=255, null=True)),
                ('sleep', models.BooleanField(default=False)),
                ('reception', models.CharField(blank=True, max_length=50, null=True)),
                ('provision', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.ImageField(blank=True, null=True, upload_to='media')),
                ('description', models.TextField(blank=True)),
                ('delete', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
    ]
