# Generated by Django 5.1.3 on 2024-12-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('gps', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('hourly', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=255)),
                ('ppe', models.CharField(max_length=255)),
                ('tools', models.CharField(max_length=255)),
                ('sleep', models.BooleanField(default=False)),
                ('reception', models.CharField(max_length=50)),
                ('provision', models.CharField(max_length=255)),
                ('plan', models.ImageField(upload_to='media')),
                ('description', models.TextField(blank=True)),
                ('delete', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
    ]
