# Generated by Django 5.1.3 on 2024-12-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(blank=True, max_length=100)),
                ('un_2', models.CharField(blank=True, max_length=255)),
                ('wheight_2', models.CharField(blank=True, max_length=255)),
                ('un_3', models.CharField(blank=True, max_length=255)),
                ('wheight_3', models.CharField(blank=True, max_length=255)),
                ('un_4', models.CharField(blank=True, max_length=255)),
                ('wheight_4', models.CharField(blank=True, max_length=255)),
                ('un_5', models.CharField(blank=True, max_length=255)),
                ('wheight_5', models.CharField(blank=True, max_length=255)),
                ('un_6', models.CharField(blank=True, max_length=255)),
                ('wheight_6', models.CharField(blank=True, max_length=255)),
                ('un_8', models.CharField(blank=True, max_length=255)),
                ('wheight_8', models.CharField(blank=True, max_length=255)),
                ('un_9', models.CharField(blank=True, max_length=255)),
                ('wheight_9', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(blank=True, max_length=100)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('hours_day', models.IntegerField(blank=True)),
                ('hours_work', models.IntegerField(blank=True)),
                ('hours_wait', models.IntegerField(blank=True)),
                ('kms_total', models.IntegerField(blank=True)),
                ('kms_filled', models.IntegerField(blank=True)),
                ('kms_empty', models.IntegerField(blank=True)),
                ('wheight', models.IntegerField(blank=True)),
                ('diesel', models.IntegerField(blank=True)),
                ('adblue', models.IntegerField(blank=True)),
            ],
        ),
    ]
