# Generated by Django 5.1.3 on 2025-01-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wheight_2',
            new_name='weight_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='wheight_3',
            new_name='weight_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='wheight_4',
            new_name='weight_4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='wheight_5',
            new_name='weight_5',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='wheight_6',
            new_name='weight_6',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='wheight_8',
            new_name='weight_8',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='wheight_9',
            new_name='weight_9',
        ),
        migrations.RenameField(
            model_name='working',
            old_name='wheight',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='product',
            name='month_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='working',
            name='month_year',
            field=models.DateField(),
        ),
    ]
