# Generated by Django 5.1.3 on 2024-12-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=10)),
                ('onu', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=350)),
                ('nsa', models.CharField(blank=True, max_length=350, null=True)),
                ('labels', models.CharField(blank=True, max_length=20, null=True)),
                ('packing_group', models.IntegerField(blank=True, default=0, null=True)),
                ('tunnel_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ppe', models.TextField(blank=True, null=True)),
                ('risks', models.TextField(blank=True, null=True)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
    ]
