# Generated by Django 5.1.3 on 2024-12-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adr',
            name='nsa',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
