# Generated by Django 5.1.3 on 2024-12-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0002_alter_adr_nsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adr',
            name='labels',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adr',
            name='packing_group',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='adr',
            name='ppe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adr',
            name='risks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adr',
            name='tunnel_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
