# Generated by Django 5.1.3 on 2024-12-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
