# Generated by Django 5.1.3 on 2024-12-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_account_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
