# Generated by Django 5.1.3 on 2024-12-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeDaytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hour_arrival', models.TimeField()),
                ('km_arrival', models.IntegerField()),
                ('trailer', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('lights', models.CharField(blank=True, max_length=100)),
                ('tires', models.CharField(blank=True, max_length=100)),
                ('wheight', models.BooleanField(default=False)),
                ('hour_start', models.TimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('compled', models.BooleanField(default=False)),
                ('formel', models.CharField(default='change', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FactoryDaytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hour_arrival', models.TimeField()),
                ('km_arrival', models.IntegerField()),
                ('start_work', models.TimeField(blank=True, null=True)),
                ('end_work', models.TimeField(blank=True, null=True)),
                ('cmr', models.TextField(blank=True)),
                ('command', models.TextField(blank=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('wheight', models.IntegerField(blank=True, null=True)),
                ('hour_start', models.TimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('km_filled', models.IntegerField(blank=True, null=True)),
                ('km_empty', models.IntegerField(blank=True, null=True)),
                ('compled', models.BooleanField(default=False)),
                ('formel', models.CharField(default='factory', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GasoilDaytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hour_arrival', models.TimeField()),
                ('km_arrival', models.IntegerField()),
                ('diesel', models.IntegerField(blank=True, null=True)),
                ('adblue', models.IntegerField(blank=True, null=True)),
                ('hour_start', models.TimeField(blank=True, null=True)),
                ('compled', models.BooleanField(default=False)),
                ('formel', models.CharField(default='gasoil', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StartDaytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_driver', models.CharField(max_length=100)),
                ('truck', models.CharField(max_length=100)),
                ('trailer', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('city_start', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('hour_start', models.TimeField()),
                ('km_start', models.IntegerField()),
                ('city_end', models.CharField(blank=True, max_length=100)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('hour_end', models.TimeField(blank=True, null=True)),
                ('km_end', models.IntegerField(blank=True, null=True)),
                ('work', models.JSONField(default=list)),
                ('compled', models.BooleanField(default=False)),
                ('formel', models.CharField(default='start', max_length=50)),
            ],
        ),
    ]
