# Generated by Django 5.1.3 on 2024-12-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorydaytime',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
