# Generated by Django 5.1.3 on 2024-12-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daytime', '0002_alter_changedaytime_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorydaytime',
            name='name_driver',
        ),
    ]
