# Generated by Django 5.1.3 on 2024-12-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daytime', '0003_remove_factorydaytime_name_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changedaytime',
            name='name_driver',
        ),
        migrations.RemoveField(
            model_name='gasoildaytime',
            name='name_driver',
        ),
    ]
