# Generated by Django 5.1.3 on 2024-12-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytime', '0005_startdaytime_last_loading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startdaytime',
            name='trailer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
