# Generated by Django 5.1.3 on 2024-12-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytime', '0006_alter_startdaytime_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startdaytime',
            name='work',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
