# Generated by Django 5.1.3 on 2024-12-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daytime', '0007_alter_startdaytime_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factorydaytime',
            old_name='km_empty',
            new_name='km_emptied',
        ),
    ]
