# Generated by Django 5.1.3 on 2024-12-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytime', '0008_rename_km_empty_factorydaytime_km_emptied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorydaytime',
            name='wheight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
