# Generated by Django 5.1.3 on 2024-12-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytime', '0009_alter_factorydaytime_wheight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorydaytime',
            name='wheight',
            field=models.IntegerField(default=0),
        ),
    ]
