# Generated by Django 5.1.3 on 2024-12-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daytime', '0010_alter_factorydaytime_wheight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changedaytime',
            old_name='hour_arrival',
            new_name='arrival_hour',
        ),
        migrations.RenameField(
            model_name='changedaytime',
            old_name='compled',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='changedaytime',
            old_name='wheight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='factorydaytime',
            old_name='hour_arrival',
            new_name='arrival_hour',
        ),
        migrations.RenameField(
            model_name='factorydaytime',
            old_name='compled',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='factorydaytime',
            old_name='wheight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='factorydaytime',
            old_name='start_work',
            new_name='work_start',
        ),
        migrations.RenameField(
            model_name='gasoildaytime',
            old_name='hour_arrival',
            new_name='arrival_hour',
        ),
        migrations.RenameField(
            model_name='gasoildaytime',
            old_name='compled',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='startdaytime',
            old_name='compled',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='startdaytime',
            old_name='name_driver',
            new_name='driver_name',
        ),
        migrations.RenameField(
            model_name='startdaytime',
            old_name='last_loading',
            new_name='last_load',
        ),
    ]
