# Generated by Django 5.1.3 on 2024-12-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytime', '0011_rename_hour_arrival_changedaytime_arrival_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changedaytime',
            name='cmr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changedaytime',
            name='command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changedaytime',
            name='product',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
