# Generated by Django 5.1.3 on 2024-12-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytime', '0012_changedaytime_cmr_changedaytime_command_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changedaytime',
            old_name='formel',
            new_name='formal',
        ),
        migrations.RenameField(
            model_name='factorydaytime',
            old_name='formel',
            new_name='formal',
        ),
        migrations.RenameField(
            model_name='gasoildaytime',
            old_name='formel',
            new_name='formal',
        ),
        migrations.RenameField(
            model_name='startdaytime',
            old_name='formel',
            new_name='formal',
        ),
        migrations.AlterField(
            model_name='changedaytime',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
